# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase-Realm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase-Realm

  target 'Firebase-RealmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Firebase-RealmUITests' do
    # Pods for testing
  end
  pod 'FirebaseAuth'
	pod 'FirebaseFirestore'
	pod 'FirebaseCore'
	pod 'Firebase/Database'	

end


